// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: meshtastic/cannedmessages.proto

package gomeshproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canned message module configuration.
type CannedMessageModuleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Predefined messages for canned message module separated by '|' characters.
	Messages string `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
}

func (x *CannedMessageModuleConfig) Reset() {
	*x = CannedMessageModuleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_cannedmessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CannedMessageModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CannedMessageModuleConfig) ProtoMessage() {}

func (x *CannedMessageModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_cannedmessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CannedMessageModuleConfig.ProtoReflect.Descriptor instead.
func (*CannedMessageModuleConfig) Descriptor() ([]byte, []int) {
	return file_meshtastic_cannedmessages_proto_rawDescGZIP(), []int{0}
}

func (x *CannedMessageModuleConfig) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

var File_meshtastic_cannedmessages_proto protoreflect.FileDescriptor

var file_meshtastic_cannedmessages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x63, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x22, 0x37, 0x0a,
	0x19, 0x43, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x6e, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x65,
	0x65, 0x6b, 0x73, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x42, 0x19, 0x43,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f,
	0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0xaa, 0x02, 0x14, 0x4d,
	0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0xba, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshtastic_cannedmessages_proto_rawDescOnce sync.Once
	file_meshtastic_cannedmessages_proto_rawDescData = file_meshtastic_cannedmessages_proto_rawDesc
)

func file_meshtastic_cannedmessages_proto_rawDescGZIP() []byte {
	file_meshtastic_cannedmessages_proto_rawDescOnce.Do(func() {
		file_meshtastic_cannedmessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshtastic_cannedmessages_proto_rawDescData)
	})
	return file_meshtastic_cannedmessages_proto_rawDescData
}

var file_meshtastic_cannedmessages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtastic_cannedmessages_proto_goTypes = []interface{}{
	(*CannedMessageModuleConfig)(nil), // 0: meshtastic.CannedMessageModuleConfig
}
var file_meshtastic_cannedmessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtastic_cannedmessages_proto_init() }
func file_meshtastic_cannedmessages_proto_init() {
	if File_meshtastic_cannedmessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshtastic_cannedmessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CannedMessageModuleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshtastic_cannedmessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_cannedmessages_proto_goTypes,
		DependencyIndexes: file_meshtastic_cannedmessages_proto_depIdxs,
		MessageInfos:      file_meshtastic_cannedmessages_proto_msgTypes,
	}.Build()
	File_meshtastic_cannedmessages_proto = out.File
	file_meshtastic_cannedmessages_proto_rawDesc = nil
	file_meshtastic_cannedmessages_proto_goTypes = nil
	file_meshtastic_cannedmessages_proto_depIdxs = nil
}
